import React from "react";
import type { Metadata } from "next";
import "./globals.css";
import NextAuthSessionProvider from "@/providers/sessionProvider";
import ToastProvider from "@/toast/ToastProvider";

export const metadata: Metadata = {
  title: "Site Saúde",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ToastProvider>
          <NextAuthSessionProvider>{children}</NextAuthSessionProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
