import React from "react";
import type { Metadata } from "next";
import { ToastContainer } from "react-toastify";
import "./globals.css";
import NextAuthSessionProvider from "@/providers/sessionProvider";

export const metadata: Metadata = {
  title: "Site Saúde",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ToastContainer />
        <NextAuthSessionProvider>{children}</NextAuthSessionProvider>
      </body>
    </html>
  );
}
